config/routes.rb
Ttmesaj::Application.routes.draw do
  resources :messages

  root :to => 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :number

  validates :number, :body, :presence => true

  GSM_REGEX = /^5\d{9}$/

  validates :number, :format => {:with => GSM_REGEX}
  #before_create :send_message, :if => lambda{ Rails.env.production?}
  before_create :send_message

  def send_message
    client = Savon::Client.new("http://ws.ttmesaj.com/service1.asmx?WSDL")
    response = client.request :web, :send_single_sms, body: {
        "username" => "kullanici adi",
        "password" => "sifre",
        "numbers" => "0#{self.number}",
        "message" => "#{self.body}",
        "origin" => "origin",
        "sd" => "",
        "ed" => "" }

    if response.success?
      res = response.to_hash
      if res
        self.status = res[:send_single_sms_response][:send_single_sms_result]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end



  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ttmesaj</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Numara<br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    Mesaj<br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Gönder" %>
  </div>
<% end %>

app/views/messages/index.html.erb
<h1>Gönderilen Mesajlar</h1>

<table>
  <tr>
    <th>Numara</th>
    <th>Mesaj</th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.number %></td>
    <td><%= message.body %></td>
    <td><%= link_to 'Show', message %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Yeni Sms Gönder', new_message_path %>

app/views/messages/new.html.erb
<h1>Yeni Sms</h1>

<%= render 'form' %>

<%= link_to 'Geri Dön', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numara:</b>
  <%= @message.number %>
</p>

<p>
  <b>Mesaj:</b>
  <%= @message.body %>
</p>
<p>
  <b>Durum</b>
    <%= @message.status %>
</p>

<%= link_to 'Back', messages_path %>